[server]
debug = false
domain = "CHANGE THIS"
port = 2006

[database]
host = "localhost"
user = "CHANGE THIS"
password = "CHANGE THIS"
db = "CHANGE THIS"
autocommit = true

[redis]
host = "localhost"
username = "CHANGE THIS IF ANYTHING"
password = "CHANGE THIS IF ANYTHING"
port = 6379

[api]
key = "CHANGE THIS"

[api.mirrors]
chimu = "https://api.chimu.moe/v1/"
katsu = "https://katsu.moe/"
nerinyan = "https://api.nerinyan.moe/"

[fun]
rank_all_maps = true